name: 'Release Notes Generator'
description: 'Generates a changelog and creates a GitHub release using gen_release_notes.sh'

inputs:
  tag_name:
    description: 'The tag name for the new release'
    required: true
  config:
    description: 'Additional configuration arguments for the script'
    required: false
    default: ''
  create_release:
    description: 'Automatically create a GitHub Release'
    required: false
    default: 'true'
  github_token:
    description: 'GitHub token for release creation'
    required: false
    default: ${{ github.token }}

outputs:
  changelog:
    description: 'The generated release notes text'
    value: ${{ steps.run-gen.outputs.changelog }}

runs:
  using: "composite"
  steps:
    - name: Run Generator
      id: run-gen
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/gen_release_notes.sh"
        "${{ github.action_path }}/gen_release_notes.sh" ${{ inputs.tag_name }} ${{ inputs.config }} > result_changelog.md
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat result_changelog.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      if: ${{ inputs.create_release == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        gh release create "${{ inputs.tag_name }}" \
          --title "Release ${{ inputs.tag_name }}" \
          --notes-file result_changelog.md